spring.data.mongodb.uri=mongodb://localhost:27017/smart_clinic
server.port=8080

# SMS API Credentials (Fast2SMS)
# Get your key from: https://www.fast2sms.com/dashboard/dev-api
sms.api.key=YyAj6sW5XQOr7lqve1nuBFhT2KbDi9pz4mkxNaPgJGfL0RZHdwoV0dhIQqwTbysDkZgOmLePGW39jYz8
spring.main.allow-bean-definition-overriding=true
